#Define the amount of slots you wish the server to start with here.
#The maximum amount of slots should be the same as in your server.properties.
public-slot-count: 20
reserved-slot-count: 10
server-full-message: "The server is currently full"